# Local directories
task_name: SemEval
data_dir: /home/buddhi/Albert/en/Data/
output_dir: gs://buddhi_albert/sts-keras/
cached_dir: gs://buddhi_albert/sts-keras/cache
pred_file: gs://buddhi_albert/sts-keras/results.csv
tensorboard_logs: gs://buddhi_albert/model_logs/ 
# Model hub url
albert_hub_module_handle: gs://buddhi_albert/sts-keras/albert_model_hub_v2
# Training params
spm_model_file: /home/buddhi/Albert/en/Keras/albert_module_hub_v2/assets/30k-clean.model
do_train: true
learning_rate: 2e-4
do_eval: true
do_test: false
do_lower_case: true
sequence_len: 512
num_train_epochs: 10
train_batch_size: 16
eval_batch_size: 32
test_batch_size: 8
warmup_steps: 200
save_checkpoints_steps: 1000
iterations_per_loop: 1000
#init_checkpoint: gs://model.ckpt-0.data-00000-of-00001
# Google cloud compute params
use_tpu: True
optimizer: adamw
tpu_name: tpu-v2
gcp_project: buddhi-tpu
